language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  # newer versions of docutils dropped support for Python 3.4
  - if [ $TRAVIS_PYTHON_VERSION == "3.4" ]; then pip install docutils==0.15.2; else pip install docutils; fi
  # easy_install fails to install wstool as a dependency
  # https://github.com/vcstools/rosinstall/pull/116
  - pip install wstool
  - pip install -U setuptools tox tox-travis
  - python setup.py install  # to make pip install dependencies
  - sudo apt-get clean
  - sudo apt-get update && sudo apt-get install -qq zsh
  - python -m pip install nose PyYAML
  - python -c 'import sys; print(sys.path)'
# command to run tests
script:
  - export ROSINSTALL_SKIP_PYTHON3=1
  - tox
  # Install rosinstall from pip and perform a sanity check
  - pip install --upgrade rosinstall wstool
  - rosws
notifications:
  email: false
matrix:
  allow_failures: []
